Synced commit 881d540 go-1,15

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -57,6 +57,26 @@ override_dh_prep:
 	done
 
 
+override_dh_auto_test-arch:
+ifeq (true, $(RUN_TESTS))
+	set -ex; \
+		cd src; \
+		export PATH="$(GOROOT)/bin:$$PATH"; \
+		eval "$$(go tool dist env)"; \
+		bash run.bash -k -no-rebuild;
+	# -k           keep going even when error occurred
+	# -no-rebuild  don't rebuild std and cmd packages
+
+	# On linux/amd64 run.bash installs some race enabled standard library
+	# packages. Delete them again to avoid accidentally including them in
+	# the package.
+	set -ex; \
+		export PATH="$(GOROOT)/bin:$$PATH"; \
+		eval "$$(go tool dist env)"; \
+		rm -rf "$(GOROOT)/pkg/$${GOOS}_$${GOARCH}_race/"
+else
+	# skip the tests on platforms where they fail
+endif
 	# Remove GOCACHE files
 	rm -rf pkg/obj
 
